Domain Name: nic.ms
Registry Domain ID: 8637-CoCCA
Registrar URL: https://secure.domains.mninet.ms
Updated Date: 2024-01-24T16:18:05Z
Creation Date: 1998-09-01T12:00:00Z
Registry Expiry Date: 2099-09-01T00:00:00Z
Registrar Registration Expiration Date: 2099-09-01T00:00:00Z
Domain Status: clientTransferProhibited https://icann.org/epp#clientTransferProhibited
Domain Status: serverTransferProhibited https://icann.org/epp#serverTransferProhibited
Domain Status: clientDeleteProhibited https://icann.org/epp#clientDeleteProhibited
Domain Status: serverDeleteProhibited https://icann.org/epp#serverDeleteProhibited
Registrar: MNINET Registrar
Registrar Address: Olveston Drive
Olveston
Montserrat
Registrar Country: MS
Registrar Abuse Contact Email: sales@mninet.ms
Registrar Abuse Contact Phone: 
Registry Registrant ID: 53629-CoCCA
Registrant Name: MNI Networks
Registrant Organization: 
Registrant Street: olveston
Registrant City: montserrat
Registrant State/Province: 
Registrant Postal Code: 
Registrant Country: MS
Registrant Phone: +0 16644916386
Registrant Email: kingsley.howe@mninet.ms
Registry Admin ID: 53630-CoCCA
Admin Name: Denzil West
Admin Organization: 
Admin Street: mni networks
Admin City: montserrat
Admin State/Province: 
Admin Postal Code: 
Admin Country: MS
Admin Phone: +0 16644916386
Admin Email: westd@gov.ms
Registry Tech ID: 53627-CoCCA
Tech Name: Dave Williams
Tech Organization: 
Tech Street: mni networks
Tech City: montserrat
Tech State/Province: 
Tech Postal Code: 
Tech Country: MS
Tech Phone: +0 16644916386
Tech Email: dave@gov.ms
Name Server: ns51.constellix.net
Name Server: ns21.constellix.com
Name Server: ns31.constellix.com
Name Server: ns61.constellix.net
Name Server: ns11.constellix.com
Name Server: ns41.constellix.net
DNSSEC: unsigned
>>> Last update of WHOIS database: 2024-12-04T22:11:47.574Z <<<

