Whois Server Version 3.3.2

Domain Name: nic.st
Registrar: Reserved by ST Registry
Name Server: ns1.bahnhof.net
Name Server: dns-st.bahnhof.net
Name Server: dns-au.st
Name Server: dns-us.st
Status: clientTransferProhibited, serverDeleteProhibited, serverUpdateProhibited
Updated Date: 2018-03-29
Creation Date: 1999-06-19
Expiration Date: 2035-06-19

>>> Last update of whois database: 2024-12-04T22:12:53Z <<<

The data in the WHOIS database is protected by copyright.

By submitting a WHOIS query, you agree that you will use this data only for lawful purposes according with the terms and policy that is publicly available on https://www.nic.st/terms-of-service and that, under no circumstances will you use this data to allow, enable, or otherwise support the transmission of mass unsolicited, commercial advertising or solicitations via direct mail, electronic mail, or by telephone; in contravention of any applicable data and privacy protection laws; or to enable high volume, automated, electronic processes that apply to the registry (or its systems).
Compilation, repackaging, dissemination, or other use of the WHOIS database in its entirety, or of a substantial portion thereof, is not allowed without ST Registry prior written permission.
By executing this query, in any manner whatsoever, you agree to abide by these terms. In some limited cases, domains that might appear as available in whois might not actually be available as they could be already registered and the whois not yet updated and/or they could be part of the Restricted list. In this cases, performing a check through your Registrar's (EPP check) will give you the actual status of the domain.

ST Registry reserves the right to modify or change these conditions at any time without prior or subsequent notification of any kind.

DOMAIN: nic.st

REGISTRATION-SERVICE-PROVIDER: Reserved by ST Registry
URL: www.nic.st

created-date:    1999-06-19 22:00:00
updated-date:    2018-03-29 08:01:49
expiration-date: 2035-06-19 00:00:00

registrant-organization: ST Registry
registrant-name:         ST Registry (TEM525418775359E)
registrant-street:       Travessa João de Deus C.P. 709
registrant-city:         
registrant-state:        
registrant-zip:          
registrant-country:      ST
registrant-phone:        
registrant-fax:          
registrant-email:        support@nic.st

admin-organization: ST Registry
admin-name:         ST Registry (TEM525418775359E)
admin-street:       Travessa João de Deus C.P. 709
admin-city:         
admin-state:        
admin-zip:          
admin-country:      ST
admin-phone:        
admin-fax:          
admin-email:        support@nic.st

tech-organization: Bahnhof Internet AB
tech-name:         Sao Tome Registry (TEM5254196D69171)
tech-street:       Travessa João de Deus C.P. 709
tech-city:         
tech-state:        
tech-zip:          
tech-country:      ST
tech-phone:        
tech-fax:          
tech-email:        st-registry@tecnisys.net

billing-organization: ST Registry
billing-name:         ST Registry (TEM52541B0789228)
billing-street:       Travessa João de Deus C.P. 709
billing-city:         
billing-state:        
billing-zip:          
billing-country:      ST
billing-phone:        
billing-fax:          
billing-email:        support@nic.st

nameserver: ns1.bahnhof.net
nameserver: dns-st.bahnhof.net
nameserver: dns-au.st
nameserver: dns-us.st

