Domain Name: nic.tl
Registry Domain ID: 1716879-CoCCA
Updated Date: 2023-03-30T02:47:08Z
Creation Date: 2018-10-15T12:22:51Z
Registry Expiry Date: 2025-12-31T00:00:00Z
Registrar Registration Expiration Date: 2025-12-31T00:00:00Z
Registrar: CoCCA Registry Stub Zones
Domain Status: clientRenewProhibited https://icann.org/epp#clientRenewProhibited
Domain Status: serverRenewProhibited https://icann.org/epp#serverRenewProhibited
Domain Status: clientTransferProhibited https://icann.org/epp#clientTransferProhibited
Domain Status: serverTransferProhibited https://icann.org/epp#serverTransferProhibited
Domain Status: clientDeleteProhibited https://icann.org/epp#clientDeleteProhibited
Domain Status: serverDeleteProhibited https://icann.org/epp#serverDeleteProhibited
Registry Registrant ID: 653690-CoCCA
Registrant Name: Garth Miller
Registrant Organization: CoCCA Registry Services (NZ) Limited
Registrant Street: 11a Wynyard Street
Registrant City: Auckland
Registrant State/Province: Auckland
Registrant Postal Code: 0624
Registrant Country: NZ
Registrant Phone: +64.94466370
Registrant Email: garth.miller@cocca.org.nz
Name Server: ns1.desec.io
Name Server: ns2.desec.org
DNSSEC: unsigned
URL of the ICANN Whois Inaccuracy Complaint Form: https://www.icann.org/wicf/
>>> Last update of WHOIS database: 2024-12-04T22:13:09.675Z <<<

For more information on domain status codes, please visit https://icann.org/epp

TERMS OF USE: You are not authorized to access or query our Whois
database through the use of electronic processes that are high-volume and
automated.  Whois database is provided by CoCCA as a service to the internet
community on behalf of CoCCA members.

The data is for information purposes only. CoCCA does not
guarantee its accuracy. By submitting a Whois query, you agree to abide
by the following terms of use: You agree that you may use this Data only
for lawful purposes and that under no circumstances will you use this Data
to: (1) allow, enable, or otherwise support the transmission of mass
unsolicited, commercial advertising or solicitations via e-mail, telephone,
or facsimile; or (2) enable high volume, automated, electronic processes
that apply to CoCCA it's members (or CoCCA or member computer systems). The
compilation, repackaging, dissemination or other use of this Data is
expressly prohibited.

CoCCA Helpdesk |  support@coccaregistry.org
