Domain Name: nic.td
Registry Domain ID: 20-nictd
Registry WHOIS Server: whois.nic.td
Updated Date: 2023-11-28T16:46:31.999Z
Creation Date: 2015-09-05T04:00:00.0Z
Registry Expiry Date: 2025-12-30T05:00:00.0Z
Registrar Registration Expiration Date: 2025-12-30T05:00:00.0Z
Domain Status: serverRenewProhibited https://icann.org/epp#serverRenewProhibited
Domain Status: serverTransferProhibited https://icann.org/epp#serverTransferProhibited
Domain Status: serverUpdateProhibited https://icann.org/epp#serverUpdateProhibited
Domain Status: serverDeleteProhibited https://icann.org/epp#serverDeleteProhibited
Registry Registrant ID: 23Gm7-uKUdR
Registrant Name: ADETIC
Registrant Organization: Agence de Développement des TIC
Registrant Street: Rue de Colonel Hassan Moursal Kourda
Registrant City: N'Djamena
Registrant Postal Code: 240
Registrant Country: TD
Registrant Phone: +235.66231668
Registrant Email: info@adetic.td
Registry Admin ID: wrIdr-ZwNg8
Admin Name: Batrane Mahamat Ali
Admin Organization: Agence de Développement des TIC
Admin Street: Rue de Colonel Hassan Moursal Kourda
Admin City: N'Djamena
Admin Postal Code: 240
Admin Country: TD
Admin Phone: +235.66865586
Admin Email: batrane.mahamat@adetic.td
Registry Tech ID: JtJKX-mU86v
Tech Name: Mahamat Hamid Haggar
Tech Organization: Agence de Développement des TIC
Tech Street: Rue de Colonel Hassan Moursal Kourda
Tech City: N'Djamena
Tech Postal Code: 240
Tech Country: TD
Tech Phone: +235.66231668
Tech Email: mahamat.hamid@adetic.td
Registrar: La liste des sous-domaine .td
Name Server: ns2.desec.org
Name Server: ns1.desec.io
DNSSEC: unsigned
>>> Last update of WHOIS database: 2024-12-04T21:00:11.577Z <<<

For more information on EPP status codes, please visit https://icann.org/epp

TERMS OF USE: You are not authorized to access or query our WHOIS database through the use of electronic processes that are high-volume and automated.  This WHOIS database is provided by as a service to the internet community.

The data is for information purposes only. We do not guarantee its accuracy. By submitting a WHOIS query, you agree to abide by the following terms of use: You agree that you may use this Data only for lawful purposes and that under no circumstances will you use this Data to: (1) allow, enable, or otherwise support the transmission of mass unsolicited, commercial advertising or solicitations via e-mail, telephone, or facsimile; or (2) enable high volume, automated, electronic processes.

The compilation, repackaging, dissemination or other use of this Data is expressly prohibited.
